export const MOCK_COACHES = [
  {
    id: '1',
    name: 'Marcus Vane',
    specialty: 'Strength & Conditioning',
    clientsCount: 24,
    image: require('@assets/images/coaches/coach-1.png'),
    experience: '8 Years',
    price: 4500,
    about: 'I specialize in helping athletes and fitness enthusiasts build functional strength and elite conditioning. My approach is science-based and results-driven.',
  },
  {
    id: '2',
    name: 'Sarah Chen',
    specialty: 'Yoga & Mindfulness',
    clientsCount: 18,
    image: require('@assets/images/coaches/coach-2.png'),
    experience: '5 Years',
    price: 3800,
    about: 'Focusing on the harmony between body and mind. I help my clients improve flexibility, reduce stress, and find their inner balance through specialized yoga flows.',
  },
  {
    id: '3',
    name: 'David Miller',
    specialty: 'Weight Loss & Nutrition',
    clientsCount: 32,
    image: require('@assets/images/coaches/coach-3.png'),
    experience: '12 Years',
    price: 5000,
    about: 'Transforming lives through sustainable nutrition and effective workout plans. I have helped over 300 clients reach their goal weight and maintain it.',
  },
  {
    id: '4',
    name: 'Elena Rodriguez',
    specialty: 'HIIT & Cardio',
    clientsCount: 15,
    image: require('@assets/images/coaches/coach-4.png'),
    experience: '6 Years',
    price: 4200,
    about: 'High energy, high results. My HIIT sessions are designed to torch fat and improve cardiovascular health in the most efficient way possible.',
  },
];
